### ISSUE TITLE
Проблема с запуском

### ISSUE THREAD

**Issue by gwynnbleiidd** [igorsaux/VK-ChatBot2#1]
Привет, вначале ругался на кодировку.
Прописал в main.py - # coding: utf8 в самом начале

Теперь при старте пишет:
```
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from api.plugins import *
ImportError: No module named api.plugins
```

**Comment by igorsaux** [comment]
Ошибка может быть если вы запускаете не в директорий с файлом main.py.
Если запустить так:

```
python VK-ChatBot2/main.py
```

то даже не получиться прочитать файл конфигураций. Какая у вас ОС и как запускаете? Также спасибо за небольшое исправление.

**Comment by gwynnbleiidd** [comment]
хм, запускаю я то в той директории
Запускаю на c9.io, там ubuntu идёт, а какой питон надо потому что он кажись второй даёт по умолчанию.

**Comment by igorsaux** [comment]
Кстати, очень важный момент про который я забыл упомянуть. Данная программа написана для питона версий 3.

**Comment by gwynnbleiidd** [comment]
Во :) Сейчас тогда третий подтяну

**Comment by igorsaux** [comment]
Ан, нет. В README всё указано :)

**Comment by gwynnbleiidd** [comment]
Значит мой косяк, сейчас буду искать как ему модуль скоримить.
Потому что работает сразу 2 версии, 3я стартует по pythone3

**Comment by gwynnbleiidd** [comment]
Всё, запустил.
На c9.io работает нормально, просто нужно вручную переключить питон на 3ю версию.
